export default {
  Contact: {
    Name: "Mr. Subhash B. Tatale",
    Address:
      "103-Rohini Wing, Suvidha Ambar Society, Katraj-Dhayri road, Narhe, Pune 41.",
    Phone: "+91 - 96 73 990142",
    Email: "subhash.tatale@viit.ac.in",
  },
  Details: [
    "Ph.D.(Computer Engineering), M. Tech(Information Technology)",
    "Assistant Professor in Computer Engineering",
    "Bansilal Ramnath Agarwal Charitable Trust's",
    "Vishwakarma Institute of Information Technology, Pune",
  ],
  Objective: [
    "To pursue a challenging career as a part of progressive organization where knowledge can be enhanced through research and hands-on skill. Empower students with necessary knowledge, skills, qualities and values through teaching and academic administration",
  ],
  Education: [
    "Pursuing Doctor of Philosophy (Ph.D.) in Computer Science and Engineering from K L University, Vijayawada, Andhra Pradesh.",
    "Master of Technology (M. Tech.) in Information Technology (First class,March 2012)",
    "Bachelor of Engineering (B.E.) in Computer Engineering. (First class, June 2007)",
  ],
  Experience: [
    "Assistant Professor in Computer Engineering, Vishwakarma Institute of Information Technology, Department of Information Technology since January 2010 till date.",
    "Software Engineer at Nihilent Technologies Pvt Ltd, Pune from September 2007 to December 2009.",
  ],
  Awards: [
    "Awarded as “Excellent Employee” for year 2019 by Vishwakarma Institutes",
    "Awarded as “Excellent Employee” for year 2018 by Vishwakarma Institutes",
    "Recognized as a SILVER partner faculty under Inspire- The Infosys Campus Connect Faculty Partnership Model in the year 2017",
    "Appreciated by Vishwakarma Institutes for Excellent Contribution done in preparation of NAAC Accreditation in 2016",
    "Awarded as “Excellent Employee” for year 2016 by Vishwakarma Institutes",
    "Awarded as “Excellent Employee” for year 2015 by Vishwakarma Institutes",
    "Awarded as “Excellent Employee” for year 2013 by Vishwakarma Institutes",
  ],
  Responsibilities: {
    "Institute Level Activities": [
      "Currently working as Associate Dean-Industry Relations since June 2020.",
      "Currently working as Coordinator- Alumni Relations since August 2016.",
      " Currently working as Member of IQAC, VIIT since August 2017.",
      "Worked as Assistant Dean - Industry Relations from July 2019 to May 2020",
      "Worked as a Member, NBA visits core team, VIIT, Pune.",
      "Worked as a Member, NAAC visits core team, VIIT, Pune.",
      "Worked as a Secretary, Mentor Committee, VIIT, Pune",
      "Worked as a Coordinator for distance education center at VIIT affiliated to YCMOU, Nashik from 2012 to 2014",
    ],
    "Department Level Activities": [
      "Currently working as a Liasoning Officer of Computer Engineering Department since 2017.",
      "Working as a Coordinator, Time Table Committee since 2011.",
      "Currently working as a Member, Industry Advisory Board (IAB) since 2016",
      " Worked as a Coordinator, Industry Institute Interaction Cell from 2016 to 2020.",
      "Worked as a Coordinator, Internship & Value Added Courses from 2016 to 2019.",
      "Organized Pune University approved Faculty Development Program on “Software Engineering” during December 2014.",
      "Organized Pune University approved Faculty Development Program on “Future of Data” during February 2017.",
      "Organized AICTE approved Short Term Training Program on “Block chain Technologies and its Uses Cases” during December 2020.",
    ],
    "Savitribai Phule Pune University-Level Activities": [
      "Was actively involved in TE (2015 course) syllabus revision for Software Engineering & Project Management, Software Design Methodology and Web Technology Subject.",
      "Worked as paper setter for various subjects of 2012 & 2015 courses of Computer Engineering.",
    ],
    "Other University Level Activities": [
      "Conducted, organized & attended guest lectures, FDPs, STTPs on various topics at SPPU, Mumbai, Bharti Vidyapeeth, Solapur University and Kolhapur University.",
    ],
  },
  IndustryInteraction: [
    "Currently working as SPOC for Infosys Campus Connect and Internshalaactivities.",
    "Appreciated by AICTE, New Delhi & Internshala for helping VIIT for getting all India rank 56 for internship activities in 2019.",
    "Appreciated by Infosys Ltd as an Active SPOC of Infosys Campus Connect activity in 2017.",
    "Rs. 3, 39, 700/- is generated through Infosys Campus Connect activity. More than 1000 students and 50 faculties successfully participated in this activity.",
    "Certified by Nvidia Deep Learning Institute for demonstrating competence in the completion of Fundamentals of deep learning for multiple data types in 2019",
    "Successfully completed one week FEP on “LEX based foundation program” from 18th to 25th Jan 2019 conducted by Infosys Ltd.",
    "Successfully completed 6 weeks online summer training on “Programming with python” from 21st Feb to 4th April 2019 conducted by InternshalaTrainings.",
    "Successfully completed one week MHRD sponsored FDP on Artificial Intelligence & Machine Learning at VJTI, Mumbai under PMMMNMTT scheme in December 2018.",
    "Successfully completed one week Winter School in Software Engineering (WSSE-17) organized by ACM India in association with Tata Research Development & Design Centre (TRDDC), Pune in 2017.",
    "Successfully completed Three Days FEP on “User Interface Technologies “ organized by Infosys Ltd, Pune",
    "Successfully completed one week FEP on “Business Intelligence” organized by Infosys Ltd, Pune",
    "Successfully completed two weeks FEP on “Design & Analysis of Algorithms“ organized by Persistent Systems, Pune",
    "Successfully completed two weeks Mission 10X workshop organized by Wipro Systems, Pune",
    "Successfully organized one week Faculty Development Program on “Software Engineering” in association with GS Lab Pvt.Ltd., Pune in 2014.",
    "Successfully organized two days Faculty Development Program on “Future of Data” in association with Persistent Systems Ltd., Pune in 2018.",
    "Successfully organized two days Industry Executive Program on “Cyber Security” in association with ISACA, Pune in 2019.",
    "Successfully organized one week Faculty Development Program on “Recent Trends in Information Technology” in association with TCS, Pune in December 2018.",
    "Strong collaboration with e-zest, synerzip, GS Lab, Prototech Solutions, PRGX limited for sponsored projects for UG/PG students, Internships and Jobs.",
    "Successfully completed audit process of VIIT alumni Association.",
    "Launched web portal and mobile application for Alumni activity.",
    "Established VIIT alumni association chapter at United States.",
    "Successfully completed various courses of NPTEL, Coursera, Udemy.",
    "Established Centre of Excellence in Business Intelligence during January 2021.",
  ],
  ResearchAndAcademics: {
    Research: [
      "Received Best Research Paper Award to article published in ICCUBEA 2019.",
      "Active collaboration with research organizations like CDAC, New Delhi & IISER, Pune for research projects.",
    ],
    "Courses Taught": [
      "Principles of Programming Language, Discrete Mathematics, Data Structures for Second Year classes.",
      "Software Engineering, Web Technology, Software Modeling & Design for Third Year classes.",
      "Software Architecture, Business Intelligence, Design & Analysis of Algorithms, Software Testing, Object Oriented Modeling & Design for Fourth Year classes",
    ],
    "Student Feedback & Results": [
      "Average student feedback of the taught courses is more than 8 out of 10.",
      "Average result of the taught courses is more than 90%.",
    ],
  },
  OtherActivities: [
    "Reviewer of International Conference on Communication, Information and Computing Technology-2021, SPIT, Mumbai.",
    "Reviewer of 5th International Conference On Computing, Communication, Control And Automation (ICCUBEA) 2019, PCCOE, Pune",
    "Reviewer of International Journal for Engineering Applications & Technology",
    "Judge for Technical Research Paper Competition for Students (TRPCS conference) at G. H. Raisoni College of Engineering & Management, Wagholi.",
    "Session on “Web Technology”, at Trinity Academy of Engineering, Pune",
    "Sessions on “Mathematics for computing”, at Amplify Mindware academy for Development of Education & Research, Pune",
    "Session conducted on “Software Engineering” at PDEA’s College of Engineering, Pune",
  ],
};
